server {
    listen 80;
    server_name _;

    location = /learncb {
        return 301 https://jacobluo.github.io/learncb/;
    }

    location ^~ /learncb/ {
        return 301 https://jacobluo.github.io$request_uri;
    }

    location / {
        return 301 https://jacobluo.github.io/learncb$request_uri;
    }
}
